### ISSUE TITLE
Remove Mockup and implement actual booking functionality

### ISSUE THREAD

**Issue by shriyansnidhish** [shriyansnidhish/Carry-a-way#33]
As a user, I should be able to book a trip for shipping respective baggage with the courier service of my choice. 
Upon login I should be able to enter the Source, Destination, arrival date, number of baggage and search for available courier services and should be able to see the pricing for above selected options, confirm the booking  and I should get the booking reference number.

Acceptance criteria - 
- Complete booking functionality should work.

**Comment by sivapraneeth21** [comment]
Moved to sprint 3.
