### ISSUE TITLE
Remove Mockup and implement actual pricing functionality

### ISSUE THREAD

**Issue by shriyansnidhish** [shriyansnidhish/Carry-a-way#34]
As a user, I should be able to see the pricing of all the available courier options for the selected source, destination, arrival date and number of baggage.

Acceptance Criteria - 
- User should be able to see the pricing for the selected details.

**Comment by sivapraneeth21** [comment]
Moved to sprint 3.

**Comment by sivapraneeth21** [comment]
Moved to sprint 4 due to implementation issue in payment authorizarion

**Comment by shriyansnidhish** [comment]
Functionality implemented, hence closing this user story
